# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306b282dacb77df4dfcd4a1ff617d6f8183300d345d37136309590dfa723b871b16e21a73722f556eac3e8655a44ac5ebcaee813874b19baeb470ba1b4f49272

test:
  secret_key_base: c569b2203003e93a64365036ebd6e946bc8a92774b15fccba4bd2778e546cb0c06b40824951c84f6bb95ca931ccde13a6cb6a7a2914a846bf82c037820c1cde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
